'use strict';
const el=id=>document.getElementById(id), ids=['level','gamma','temp','g','sigma'];
const series=[['exact','Continuum reference','#273b35',''],['positive','1B: positive only','#b34d14','7 3'],['normal','1B: positive, normalised','#7552a4','2 3'],['both','1B: both partners','#187356',''],['signed','1A: signed partners','#176399','10 3 2 3'],['double','Double delta: zero-frequency approximation','#956314','4 4']];
function plot(id,rows,curves,xlabel,ylabel){const W=Math.max(340,Math.round(el(id).getBoundingClientRect().width)),H=300,L=70,R=20,T=18,B=54,x0=rows[0].x,x1=rows.at(-1).x,ymax=Math.max(1e-12,...rows.flatMap(r=>curves.map(c=>r[c[0]])))*1.08;const X=x=>L+(x-x0)/(x1-x0)*(W-L-R),Y=y=>H-B-y/ymax*(H-T-B);let s=`<title>${xlabel}; ${ylabel}</title>`;for(let i=0;i<=4;i++){let y=ymax*i/4;s+=`<path d="M${L},${Y(y)}H${W-R}" stroke="#e0e6e1"/><text x="${L-10}" y="${Y(y)+4}" text-anchor="end">${y<.01?y.toExponential(1):y.toFixed(y<10?2:0)}</text>`;}for(let i=0;i<=4;i++){const x=x0+(x1-x0)*i/4;s+=`<text x="${X(x)}" y="${H-B+23}" text-anchor="middle">${x.toFixed(2)}</text>`;}for(const [k,label,color,dash]of curves){s+=`<path fill="none" stroke="${color}" stroke-width="2.5" stroke-dasharray="${dash}" d="${rows.map((r,i)=>`${i?'L':'M'}${X(r.x).toFixed(2)},${Y(r[k]).toFixed(2)}`).join(' ')}"><title>${label}</title></path>`;}if(id==='spectrum'&&curves.some(c=>c[0]==='double'))s+=`<text x="${W-R-4}" y="${Math.max(T+12,Y(rows[0].double)-8)}" text-anchor="end" style="fill:#956314;paint-order:stroke;stroke:white;stroke-width:4px;font-weight:650">Double delta (static)</text>`;s+=`<text x="${W/2}" y="${H-8}" text-anchor="middle">${xlabel}</text><text transform="translate(18,${(H-B+T)/2}) rotate(-90)" text-anchor="middle">${ylabel}</text>`;el(id).setAttribute('viewBox',`0 0 ${W} ${H}`);el(id).innerHTML=s;}
let cached,frame;
function update(){const p=Object.fromEntries(ids.map(id=>[id,+el(id).value]));for(const id of ids)el(id+'Out').value=id==='temp'?`${p[id]} K`:id==='g'?`${p[id].toFixed(2)} eV/Å`:`${p[id].toFixed(3)} eV`;const start=performance.now();const dd=Model.doubleDelta(p),s=Model.samples(p),rows=Array.from({length:151},(_,i)=>{const x=i*.004;return {x,double:dd,exact:Model.exact(x,p),...Model.broaden(x,p,s)};});cached={p,rows};draw();plot('dos',Array.from({length:241},(_,i)=>{const x=-1.5+i/80;return{x,rho:Model.rho(x,p)};}),[['rho','Local DOS','#187356','']],'Electron energy ε − μ (eV)','Local DOS (1/eV)');plot('zeroPlot',Array.from({length:161},(_,i)=>{const x=-1+i/80,q={...p,level:x};return{x,thermal:Model.zero(q),analytic:Model.zero({...q,temp:0})};}),[['analytic','Published T = 0 limit','#273b35','6 4'],['thermal','Selected temperature','#187356','']],'Level energy εd − μ (eV)','η(0) / ℏ (Å⁻²)');el('status').textContent=`At this level: η(0)/ℏ = ${rows[0].exact.toPrecision(5)} Å⁻². kBT = ${(Model.kb*p.temp).toFixed(4)} eV.`;el('timing').textContent=`Numerical continuum integration; zero-frequency limits evaluated explicitly. Updated in ${Math.round(performance.now()-start)} ms.`;}
function draw(){if(!cached)return;const curves=series.filter(c=>el('show-'+c[0]).checked);plot('spectrum',cached.rows,curves.length?curves:[series[0]],'Observation energy E = ℏω (eV)','η(E) / ℏ (Å⁻²)');const z=cached.rows[0];el('results').innerHTML=series.map(([key,label])=>`<tr><th scope="row">${label}</th><td>${z[key].toPrecision(5)}</td><td>${key==='exact'?'—':z.exact===0?'—':(100*(z[key]/z.exact-1)).toFixed(1)+'%'}</td></tr>`).join('');}
for(const id of ids)el(id).addEventListener('input',()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);});for(const [k]of series)el('show-'+k).addEventListener('change',draw);
el('reset').onclick=()=>{for(const [k,v]of Object.entries({level:0,gamma:.2,temp:0,g:1,sigma:.05}))el(k).value=v;update();};
el('download').onclick=()=>{const {p,rows}=cached;const text='# '+JSON.stringify(p)+'\n# friction units: hbar/angstrom^2; one spin channel\nE_eV,reference,positive_1B,normalised_1B,both_1B,signed_1A,double_delta_static\n'+rows.map(r=>[r.x,r.exact,r.positive,r.normal,r.both,r.signed,r.double].join(',')).join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='resonant-level-friction.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
update();

window.addEventListener("resize",()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);});
